Epoch 0 | Loss: 0.2165
Epoch 20 | Loss: 0.1467
Epoch 40 | Loss: 0.1795
Epoch 60 | Loss: 0.2176
Epoch 80 | Loss: 0.1807
Epoch 100 | Loss: 0.1747
Epoch 120 | Loss: 0.1595
Epoch 140 | Loss: 0.1526
Epoch 160 | Loss: 0.1489
Epoch 180 | Loss: 0.1648
Epoch 200 | Loss: 0.1891
Epoch 220 | Loss: 0.1847
Epoch 240 | Loss: 0.1665
Epoch 260 | Loss: 0.1571
Epoch 280 | Loss: 0.1217
Epoch 300 | Loss: 0.1723
Epoch 320 | Loss: 0.1514
Epoch 340 | Loss: 0.1749
Epoch 360 | Loss: 0.1431
Epoch 380 | Loss: 0.1746
Epoch 400 | Loss: 0.1817
Epoch 420 | Loss: 0.1414
Epoch 440 | Loss: 0.1476
Epoch 460 | Loss: 0.1119
Epoch 480 | Loss: 0.1316
Epoch 500 | Loss: 0.1434
Epoch 520 | Loss: 0.1569
Epoch 540 | Loss: 0.1320
Epoch 560 | Loss: 0.1281
Epoch 580 | Loss: 0.1183
Traceback (most recent call last):
  File "D:\TU-Delft\Tech_star\repo_test\Energydiff\diffusion_again\main.py", line 101, in <module>
    filepath = os.path.join(save_path, f"wandb_sample_epoch{epoch}.png")
TypeError: plot_and_save_normalized_data() got an unexpected keyword argument 'original'
